name: Build & Release NCC Bundle

on:
  push:
    branches:
      - master

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        run: pnpm i -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Generate SQL File
        run: npx prisma migrate diff --from-empty --to-schema-datamodel prisma/schema.prisma --script -o bundle/generated.sql

      - name: Build NestJS
        run: pnpm build

      - name: Install NCC
        run: pnpm install -g @vercel/ncc

      - name: Bundle with NCC
        run: |
          mkdir -p bundle
          ncc build dist/main.js -o bundle

      - name: Create zip file
        run: |
          cd bundle
          zip -r ../bundle.zip .
          cd ..

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ncc-${{ github.run_number }}
          name: 'NCC Build ${{ github.run_number }}'
          draft: false
          prerelease: false
          files: bundle.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
